import mongoose from 'mongoose';

const invoiceSchema = new mongoose.Schema(
  {
    invoiceNumber: {
      type: String,
      required: false, // Will be auto-generated by pre-save hook
      unique: true,
      sparse: true, // Allows multiple null values but enforces uniqueness for non-null values
    },
    subscriptionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Subscription',
      required: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    planName: {
      type: String,
      required: true,
    },
    planDuration: {
      type: Number,
      required: true,
    },
    amount: {
      type: Number,
      required: true,
    },
    paymentMethod: {
      type: String,
      required: true,
      enum: ['upi', 'cash', 'mixed'],
    },
    upiAmount: {
      type: Number,
      default: 0,
    },
    cashAmount: {
      type: Number,
      default: 0,
    },
    invoiceDate: {
      type: Date,
      default: Date.now,
    },
    startDate: {
      type: Date,
      required: true,
    },
    endDate: {
      type: Date,
      required: true,
    },
    status: {
      type: String,
      enum: ['paid', 'cancelled', 'refunded'],
      default: 'paid',
    },
  },
  {
    timestamps: true,
  }
);

const Invoice = mongoose.model('Invoice', invoiceSchema);

// Generate invoice number
invoiceSchema.pre('save', async function (next) {
  // Only generate invoice number for new documents that don't have one
  if (!this.isNew || this.invoiceNumber) {
    return next();
  }
  
  try {
    // Get the latest invoice number to ensure uniqueness
    const latestInvoice = await Invoice.findOne({}, {}, { sort: { createdAt: -1 } });
    
    let nextNumber = 1;
    if (latestInvoice && latestInvoice.invoiceNumber) {
      // Extract the number from the latest invoice
      const match = latestInvoice.invoiceNumber.match(/INV-\d{6}-(\d+)/);
      if (match) {
        nextNumber = parseInt(match[1], 10) + 1;
      }
    } else {
      // Count all invoices to get the next number
      const count = await Invoice.countDocuments();
      nextNumber = count + 1;
    }
    
    const year = new Date().getFullYear();
    const month = String(new Date().getMonth() + 1).padStart(2, '0');
    this.invoiceNumber = `INV-${year}${month}-${String(nextNumber).padStart(5, '0')}`;
    
    // Ensure uniqueness by checking if this invoice number already exists
    const existing = await Invoice.findOne({ invoiceNumber: this.invoiceNumber });
    if (existing) {
      // If exists, increment and try again
      nextNumber++;
      this.invoiceNumber = `INV-${year}${month}-${String(nextNumber).padStart(5, '0')}`;
    }
    
    next();
  } catch (error) {
    // Fallback: use timestamp-based approach
    const timestamp = Date.now();
    const random = Math.floor(Math.random() * 1000);
    this.invoiceNumber = `INV-${new Date().getFullYear()}${String(new Date().getMonth() + 1).padStart(2, '0')}-${String(timestamp).slice(-5)}${String(random).padStart(3, '0')}`;
    next();
  }
});

export default Invoice;

