import mongoose from 'mongoose';

const invoiceSchema = new mongoose.Schema(
  {
    invoiceNumber: {
      type: String,
      required: false, // Will be auto-generated by pre-save hook
      unique: true,
      sparse: true, // Allows multiple null values but enforces uniqueness for non-null values
    },
    subscriptionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Subscription',
      required: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    planName: {
      type: String,
      required: true,
    },
    planDuration: {
      type: Number,
      required: true,
    },
    amount: {
      type: Number,
      required: true,
    },
    paymentMethod: {
      type: String,
      required: true,
      enum: ['upi', 'cash', 'mixed'],
    },
    upiAmount: {
      type: Number,
      default: 0,
    },
    cashAmount: {
      type: Number,
      default: 0,
    },
    invoiceDate: {
      type: Date,
      default: Date.now,
    },
    startDate: {
      type: Date,
      required: true,
    },
    endDate: {
      type: Date,
      required: true,
    },
    status: {
      type: String,
      enum: ['paid', 'cancelled', 'refunded'],
      default: 'paid',
    },
  },
  {
    timestamps: true,
  }
);

const Invoice = mongoose.model('Invoice', invoiceSchema);

// Generate invoice number (only if not provided)
invoiceSchema.pre('save', async function (next) {
  // Only generate invoice number for new documents that don't have one
  // If invoiceNumber is already set (from controller), skip generation
  if (!this.isNew || this.invoiceNumber) {
    return next();
  }
  
  try {
    // Import the utility function dynamically to avoid circular dependency
    const { generateInvoiceNumber } = await import('../utils/generateInvoiceNumber.js');
    this.invoiceNumber = await generateInvoiceNumber();
    next();
  } catch (error) {
    console.error('Error in invoice pre-save hook:', error);
    // Fallback: use timestamp-based approach
    const timestamp = Date.now();
    const random = Math.floor(Math.random() * 1000);
    this.invoiceNumber = `INV-${new Date().getFullYear()}${String(new Date().getMonth() + 1).padStart(2, '0')}-${String(timestamp).slice(-5)}${String(random).padStart(3, '0')}`;
    next();
  }
});

export default Invoice;

